### ISSUE TITLE
How can I remove elementary-tweaks?

### ISSUE THREAD

**Issue by izuolan** [I-hate-farms/elementary-tweaks#14]
I installed Tweaks from here, by method described in the README.md.

```
curl -sL  http://i-hate-farms.github.io/spores/install | sudo bash - 
sudo apt-get install elementary-tweaks
```

Now I want to delete it, but I can not do it correctly.

```
maxim@ProBook:~$ sudo apt-get remove elementary-tweaks
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  elementary-tweaks
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1,263 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 159565 files and directories currently installed.)
Removing elementary-tweaks (1.0.1) ...
Processing triggers for libglib2.0-0:amd64 (2.42.2-0ubuntu1~14.04~ricotz0) ...
sh: 1: /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher: not found
E: Problem executing scripts DPkg::Post-Invoke '/usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher'
E: Sub-process returned an error code
maxim@ProBook:~$ 
```

Now at work with other packages this error haunts me:

```
sh: 1: /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher: not found
E: Problem executing scripts DPkg::Post-Invoke '/usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher'
E: Sub-process returned an error code
```

**Stackexchange methods not solve the problem.**

1.Reinstalling libglib2.0-0 will fix this error in my case.
`sudo apt-get install --reinstall libglib2.0-0 libglib2.0-bin libglib2.0-data`

2.To remove a package use ubuntu software center or
`sudo apt-get autoremove elementary-tweaks`
To reinstall :
`sudo apt-get install --reinstall elementary-tweaks`

**Comment by xdubois** [comment]
+1
same issue here

**Comment by izuolan** [comment]
@xdubois I solved the problem, but I forgot the method. Try restart.

**Comment by 9sunrise9** [comment]
+1, do you remenber how to solve it? @izuolan

**Comment by izuolan** [comment]
@9sunrise9 Sorry, I forgot the method. You can see #4 or [here](https://github.com/elementary-tweaks/elementary-tweaks/issues/28) ~
