### ISSUE TITLE
undefined symbol: polkit_unix_process_new

### ISSUE THREAD

**Issue by PerfectCarl** [I-hate-farms/elementary-tweaks#2]
See [this thread](https://www.reddit.com/r/elementaryos/comments/3hbyez/elementarytweaks_lives_with_fixes_and_new_theme/cu64jj2)

```
[_LOG_LEVEL_INFO 15:05:06.514672] Application.vala:155: System Settings version: 2.0
[_LOG_LEVEL_INFO 15:05:06.514803] Application.vala:157: Kernel version: 3.16.0-45-generic
[_LOG_LEVEL_INFO 15:05:06.525299] Tweaks.vala:308: Activating Tweak plug
[_LOG_LEVEL_WARN 15:05:06.529713] GtkSettings.vala:48: Error loading GTK+ Keyfile settings.ini: No such file or directory
[_LOG_LEVEL_WARN 15:05:06.529839] GtkSettings.vala:69: Error getting GTK+ int setting: Key file does not have group 'Settings'
switchboard: symbol lookup error: /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/libtweaks.so: undefined symbol: polkit_unix_process_new
test@test:~$ apt-cache policy libpolkit-gobject-1-dev
libpolkit-gobject-1-dev:
  Installed: 0.105-4ubuntu2.14.04.1
  Candidate: 0.105-4ubuntu2.14.04.1
  Version table:
 *** 0.105-4ubuntu2.14.04.1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.105-4ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

**Comment by PerfectCarl** [comment]
Trying to reproduce the issue:
- works with a `x86` elementary vm with `os-daily` ppa enabled
- works with an `amd64` elementary vm (no update)
- works with an `amd64` elementary vm (fully updated)

Hum, tough one

**Comment by pappfer** [comment]
I'm facing the same problem. If there's anything I can help you to debug, please let me know.
I'm using an `amd64` elementary on a live system (not vm), fully updated. I had `ppa:mpstark/elementary-tweaks-daily` installed before, which I removed and uninstalled it's repository and then I installed your version.

**Comment by PerfectCarl** [comment]
@pappfer I pushed a new 1.0.1 version. Can you try it?

**Comment by pappfer** [comment]
Yes, works now. Thank you.

**Comment by PerfectCarl** [comment]
Thanks for your help
