### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pappfer** [I-hate-farms/elementary-tweaks#5]
Since this repository is not at Launchpad I wonder how could we contribute on translating the app.

**Comment by PerfectCarl** [comment]
We could use transifex. Which language would you like to contribute?

**Comment by pappfer** [comment]
Hungarian. It's not about me or translating it to Hungarian but to have a simple interface where anyone could translate it to their own language. So far we were using Launchpad translations, for example here are the translatable elementary projects: https://translations.launchpad.net/elementary
I wasn't sure whether Github has anything like that.

**Comment by PerfectCarl** [comment]
There are many online solutions to handle translations (transifex being the one coming to mind) and the all work with po files and git hooks.

So the technical side shouldn't be a problem :)

I'll set it up and keep this issue posted. But to be fair, I don't expect people rushing to translate this "power user" little app.

**Comment by pappfer** [comment]
Yes, it's not a priority 1 issue indeed. :) 
I just saw the app was half English and half Hungarian on my PC so I thought I'll contribute on completing the translation. I'll keep an open eye, once you set it up I'll contribute.

**Comment by pappfer** [comment]
Anyway, I have poedit on my laptop so I translated the missing Hungarian strings. Here you are: http://temp.pappfer.hu/hu.po

**Comment by PerfectCarl** [comment]
Did you regenerate the po file (I added some labels, changed others etc)?

In any case, thanks.

**Comment by pappfer** [comment]
I just downloaded the raw file from here and edited it: https://github.com/I-hate-farms/elementary-tweaks/tree/master/po

**Comment by PerfectCarl** [comment]
Well, I haven't updated it in age. 
So there might be some missing labels.

So I might ping you again very soon to have a perfect Hungarian translation file
